transferences_index:
    path:     /
    defaults: { _controller: "AppBundle:Transferences:index" }
    methods:  GET

transferences_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Transferences:show" }
    methods:  GET

transferences_new:
    path:     /new
    defaults: { _controller: "AppBundle:Transferences:new" }
    methods:  [GET, POST]

transferences_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Transferences:edit" }
    methods:  [GET, POST]

transferences_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Transferences:delete" }
    methods:  DELETE
