AppBundle\Entity\Bank:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\DebitCard:
    properties:
        cardno:
            - Length:
                min: 20
                max: 20
                minMessage: 'Card number must be exact {{ limit }} characters long'
                maxMessage: 'Card number must be exact {{ limit }} characters long'

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ownedby]
            message: "This customer has a Credit Card, please remove it before adding a new one"

AppBundle\Entity\Customer:
    properties:
        name:
            - Length:
                min: 3
                max: 15
                minMessage: 'This field has a least {{ limit }} characters long'
                maxMessage: 'This field {{ limit }} characters long'
        lastname:
            - Length:
                min: 3
                max: 15
                minMessage: 'This field has a least {{ limit }} characters long'
                maxMessage: 'This field {{ limit }} characters long'
        bank:
            - NotBlank: ~

AppBundle\Entity\Account:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [owner]
            message: "This Customer has an account already, please choose another customer"
    properties:
        type:
            - Choice:
                choices:  [Saving, Check]
                message:  Choose a valid type of bank account
        owner:
            - NotNull: ~